version: '3.8'
services:
 app:
    build:
      context: C:\Users\Johan\Documents\GitHub\docker-challenge-template\challenge2
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./challenge2:/usr/src/app
      - /usr/src/app/node_modules
 nginx:
    depends_on:
      - app
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./challenge2/nginx/nginx.conf:/etc/nginx/nginx.conf
networks:
 default:
    name: challenge2_default
